# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间、
alarm_timed: '7:00'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语）
dictum_channel: 1

girlfriend_infos:
  -
    #女友微信昵称
    wechat_name: '兰兰'
    #女友所在桂林
    city_name: '上海'
    # 从那天开始勾搭的（可空）
    #start_date: '2015-9-14'
    # 短句的最后留言（可空）
    sweet_words: '今日份の元气'
  - #女友微信昵称
    wechat_name: 'Nolancy'
    #女友所在桂林
    city_name: '上海'
    # 从那天开始勾搭的（可空）
    #start_date: '2015-9-14'
    # 短句的最后留言（可空）
    sweet_words: '今日份の元气'

  - #女友微信昵称
    wechat_name: '習、'
    #女友所在桂林
    city_name: '上海'
    # 从那天开始勾搭的（可空）
    #start_date: '2015-9-14'
    # 短句的最后留言（可空）
    sweet_words: '今日份の元气'

  - #女友微信昵称
    wechat_name: '李闯'
    #女友所在桂林
    city_name: '贵阳'
    # 从那天开始勾搭的（可空）
    #start_date: '2015-9-14'
    # 短句的最后留言（可空）
    sweet_words: '今日份の元气'
  - #女友微信昵称
    wechat_name: '伶铛'
    #女友所在桂林
    city_name: '上海'
    # 从那天开始勾搭的（可空）
    #start_date: '2015-9-14'
    # 短句的最后留言（可空）
    sweet_words: '今日份の元气'

  #如果有你多个人需要发送，则参照这个样式，复制即可
  #-
    #wechat_name: '心理班的精英团'
    #city_name: '上海'
    #start_date: '2018-11-11'
    #sweet_words: '来自你俊美的老公。'



